projectDjango/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
]

projectDjango/products/urls.py
from django.urls import path
from . import views, htmx_views

urlpatterns = [
    path('list_products/', views.list_products, name="list_products")
]

htmx_urlpatterns = [
    path('check_products/', htmx_views.check_products, name="check_product"),
    path('save_product/', htmx_views.save_product, name="save_product"),
    path('delete_product/<int:id>',
         htmx_views.delete_product, name="delete_product")
]

urlpatterns += htmx_urlpatterns

projectDjango/products/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()

    def __str__(self) -> str:
        return self.name

# python manage.py makemigrations
# python manage.py migrate

projectDjango/products/views.py
from django.shortcuts import render
from .models import Product


def list_products(request):
    products = Product.objects.all()
    return render(request, 'list_products.html', {'products': products})

projectDjango/products/templates/list_products.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/global-styles.css' %}">
    {% comment %} bootstrap CSS {% endcomment %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    <title>HTMX + Django</title>
    <link
      rel="icon"
      href="https://getbootstrap.com/docs/5.3/assets/img/favicons/favicon-32x32.png"
      sizes="32x32"
      type="image/png"
    />
  </head>
  <body>
    <div class="container mt-2">
      <form hx-post="{% url 'save_product' %}" hx-trigger="submit" hx-target="#products-list" >
        {% csrf_token %}
        <label for="id_product">Product name:</label>
        <input
          id="id_product"
          hx-get="{% url 'check_product' %}"
          hx-trigger="keyup delay:500ms"
          hx-target="#product_out"
          class="form-control mb-2"
          name="product"
          type="text"
          placeholder="product name"
        />
        <small id="product_out" class="d-block"></small>
        <label for="id_price">Price:</label>
        <input
          id="id_price"
          class="form-control mb-2"
          name="price"
          type="number"
          placeholder="price"
        />
        <button class="btn btn-primary btn-sm">save</button>
      </form>
      <div id="products-list">
        {% include "partials/htmx/all_products.html" %}
      </div>
    </div>
    {% comment %} js {% endcomment %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
      defer
    ></script>
    <script
      src="https://unpkg.com/htmx.org@2.0.0/dist/htmx.js"
      integrity="sha384-Xh+GLLi0SMFPwtHQjT72aPG19QvKB8grnyRbYBNIdHWc2NkCrz65jlU7YrzO6qRp"
      crossorigin="anonymous"
    ></script>
  </body>
</html>